# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-05-17 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20180517_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default=datetime.datetime(2018, 5, 17, 10, 12, 26, 589414, tzinfo=utc), upload_to='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='cate_choice',
            field=models.CharField(blank=True, choices=[('best', 'best'), ('hot', 'hot')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('男生', '男生'), ('女生', '女生')], max_length=100, null=True),
        ),
    ]
