# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-05-18 14:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20180517_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.CharField(default=datetime.datetime(2018, 5, 18, 14, 0, 24, 565910, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='cate_choice',
            field=models.CharField(blank=True, choices=[('hot', 'hot'), ('best', 'best')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='vote',
            field=models.CharField(blank=True, choices=[('dislike', 'dislike'), ('normal', 'normal'), ('like', 'like')], max_length=10, null=True),
        ),
    ]
