# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-05-22 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20180521_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='belong_to',
        ),
        migrations.AddField(
            model_name='buy',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='firstapp.Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cate_choice',
            field=models.CharField(blank=True, choices=[('hot', 'hot'), ('best', 'best')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='vote',
            field=models.CharField(blank=True, choices=[('dislike', 'dislike'), ('normal', 'normal'), ('like', 'like')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('女生', '女生'), ('男生', '男生')], max_length=100, null=True),
        ),
    ]
