# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-05-22 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20180522_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('send_time', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_id', to='firstapp.UserProfile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to='firstapp.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='cate_choice',
            field=models.CharField(blank=True, choices=[('best', 'best'), ('hot', 'hot')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='vote',
            field=models.CharField(blank=True, choices=[('dislike', 'dislike'), ('like', 'like'), ('normal', 'normal')], max_length=10, null=True),
        ),
    ]
