# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-05-22 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20180522_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cate_choice',
            field=models.CharField(blank=True, choices=[('hot', 'hot'), ('best', 'best')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='instationmessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instationmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='vote',
            field=models.CharField(blank=True, choices=[('normal', 'normal'), ('like', 'like'), ('dislike', 'dislike')], max_length=10, null=True),
        ),
    ]
