# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-05-23 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20180523_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='height',
            field=models.PositiveIntegerField(blank=True, default='700', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='width',
            field=models.PositiveIntegerField(blank=True, default='700', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='cate_choice',
            field=models.CharField(blank=True, choices=[('best', 'best'), ('hot', 'hot')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(height_field=models.PositiveIntegerField(blank=True, default='700', editable=False, null=True), upload_to='image', width_field=models.PositiveIntegerField(blank=True, default='700', editable=False, null=True)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='vote',
            field=models.CharField(blank=True, choices=[('normal', 'normal'), ('like', 'like'), ('dislike', 'dislike')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('男生', '男生'), ('女生', '女生')], max_length=100, null=True),
        ),
    ]
